version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:3000
      - 9229:9229
    command: npm run start:debug
    volumes:
      - /app/node_modues
      - ./src:/app/src
    env_file: .env
    depends_on:
      - redis
      - mongodb

  redis:
    image: 'redis:alpine'
    ports:
      - 6379:${REDIS_PORT}

volumes:
  mongodb_data_container:
